#!/usr/bin/env node
/**
 * Copies the third-party libraries and fonts that PdfEdit Pro needs out of
 * node_modules into www/vendor so the Android app works fully offline.
 * Runs on `npm run build` (and in GitHub Actions). Idempotent.
 */
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const nm = (...p) => path.join(root, 'node_modules', ...p);
const out = (...p) => path.join(root, 'www', 'vendor', ...p);

function copy(src, dest) {
  if (!fs.existsSync(src)) throw new Error('Missing vendor source: ' + src);
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  fs.copyFileSync(src, dest);
}

fs.rmSync(out(), { recursive: true, force: true });

// Core libraries (exact versions the HTML originally loaded from CDNs)
copy(nm('pdfjs-dist', 'build', 'pdf.min.js'),        out('pdfjs', 'pdf.min.js'));
copy(nm('pdfjs-dist', 'build', 'pdf.worker.min.js'), out('pdfjs', 'pdf.worker.min.js'));
copy(nm('pdf-lib', 'dist', 'pdf-lib.min.js'),        out('pdf-lib', 'pdf-lib.min.js'));
copy(nm('jszip', 'dist', 'jszip.min.js'),            out('jszip', 'jszip.min.js'));

// Tesseract.js OCR: main lib, worker, WASM core (LSTM builds, which is what
// Tesseract.recognize() uses by default) and English language data.
copy(nm('tesseract.js', 'dist', 'tesseract.min.js'), out('tesseract', 'tesseract.min.js'));
copy(nm('tesseract.js', 'dist', 'worker.min.js'),    out('tesseract', 'worker.min.js'));
for (const f of ['tesseract-core-lstm.wasm.js', 'tesseract-core-simd-lstm.wasm.js']) {
  copy(nm('tesseract.js-core', f), out('tesseract', 'core', f));
}
copy(nm('@tesseract.js-data', 'eng', '4.0.0_best_int', 'eng.traineddata.gz'),
     out('tesseract', 'lang', 'eng.traineddata.gz'));

// Fonts: latin subset, woff2 only, weights the app uses.
const fonts = [
  { pkg: 'inter',     family: 'Inter',      weights: [400, 500, 600, 700] },
  { pkg: 'roboto',    family: 'Roboto',     weights: [400, 700] },
  { pkg: 'open-sans', family: 'Open Sans',  weights: [400, 700] },
  { pkg: 'lato',      family: 'Lato',       weights: [400, 700] },
  { pkg: 'poppins',   family: 'Poppins',    weights: [400, 700] },
  { pkg: 'montserrat',family: 'Montserrat', weights: [400, 700] },
];
let css = '/* Generated by scripts/vendor.js — local copies of the web fonts. */\n';
for (const f of fonts) {
  for (const w of f.weights) {
    const file = `${f.pkg}-latin-${w}-normal.woff2`;
    copy(nm('@fontsource', f.pkg, 'files', file), out('fonts', file));
    css += `@font-face{font-family:'${f.family}';font-style:normal;font-weight:${w};font-display:swap;` +
           `src:url('${file}') format('woff2');}\n`;
  }
}
fs.writeFileSync(out('fonts', 'fonts.css'), css);

console.log('vendor: done ->', path.relative(root, out()));
